CREATE TABLE LAYER 
(
  LAYER_INDEX NUMBER(9) NOT NULL 
, ITERATIONS NUMBER(9) NOT NULL 
, SIDE_SIZE_POINTS NUMBER(20) NOT NULL 
, SQUARE_WIDTH BINARY_DOUBLE NOT NULL 
, CONSTRAINT LAYER_PK PRIMARY KEY (LAYER_INDEX) USING INDEX TABLESPACE "FRCTMPI" 
) 
TABLESPACE "FRCTMPD";

CREATE TABLE SQUARE 
(
  LAYER_INDEX NUMBER(9) NOT NULL
, LEFT_RE BINARY_DOUBLE NOT NULL
, TOP_IM BINARY_DOUBLE NOT NULL
, ITERATIONS NUMBER(9) NOT NULL
, SQUARE_BODY BLOB 
, CONSTRAINT SQUARE_PK PRIMARY KEY (LAYER_INDEX, LEFT_RE, TOP_IM) USING INDEX TABLESPACE "FRCTMPI" 
) 
TABLESPACE "FRCTMPD";

CREATE TABLE SQUARE_AREA
(
  LAYER_INDEX NUMBER(9) NOT NULL
, LEFT_RE BINARY_DOUBLE NOT NULL
, TOP_IM  BINARY_DOUBLE NOT NULL
, RIGHT_RE BINARY_DOUBLE NOT NULL
, BOTTOM_IM BINARY_DOUBLE NOT NULL
, ITERATIONS NUMBER(9) NOT NULL
, CONSTRAINT SQUARE_AREA_PK PRIMARY KEY (LAYER_INDEX, LEFT_RE, TOP_IM) USING INDEX TABLESPACE "FRCTMPI" 
) 
TABLESPACE "FRCTMPD";


